name: Dry Build
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14.x
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 100
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          key: v2-${{ matrix.os }}-${{ matrix.node }}-${{ github.ref }}-yarn
          path: .yarn/cache
          restore-keys: |
            v2-${{ matrix.os }}-${{ matrix.node }}-refs/heads/master-yarn
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          key: v2-${{ matrix.os }}-${{ matrix.node }}-${{ github.ref }}-node_modules
          path: node_modules
          restore-keys: |
            v2-${{ matrix.os }}-${{ matrix.node }}-refs/heads/master-node_modules
      - uses: actions/setup-node@v1
        name: Set up Node
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com
      - run: npm install -g yarn@^2.0.0-rc.27
        name: Install Yarn
      - run: yarn install --immutable
        name: Install dependencies
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn run lint
        name: Lint
      - uses: nelonoel/branch-name@v1
        name: Get branch name
        if: ${{ matrix.os != 'windows-latest' }}
      - name: Dry release
        if: ${{ matrix.os != 'windows-latest' }}
        run: yarn run release --dry-run --branches ${BRANCH_NAME}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Standard build
        if: ${{ matrix.os == 'windows-latest' }}
        run: yarn run rollup
